select  FUN.TICKER, FUN.TIPO_ABBIMA, FUN.SEGMENTO, ADM.CNPJ AS CNPJ_ADMIN , ADM.NOME AS NOME_ADMIN
from FUNDOS fun
join Administradores ADM on ADM.CNPJ = FUN.CNPJ_ADMIN
where FUN.TICKER IS NOT NULL
    ORDER BY FUN.TICKER