CREATE TABLE "WKSP_DATABASELABE"."FUNDOS" ( 
    "TICKER" VARCHAR2(6 char) NOT NULL,
    "TIPO_ABBIMA" VARCHAR2(64) NOT NULL,
    "SEGMENTO" VARCHAR2(64 char),
    "CONTA_EMIT"  NUMBER(38),
    "NUM_COTAS"  NUMBER(38),
    "RAZAO_SOCIAL" VARCHAR2(38 char),
    "CNPJ"  NUMBER(14) NOT NULL,
    "NOME_PREGAO" VARCHAR2(80 char),
    "PRAZO_DURACAO" VARCHAR2(80 char),
    "TIPO_GESTAO" VARCHAR2(60 char),
    "CNPJ_ADMIN"  NUMBER(14) NOT NULL
);

CREATE TABLE "WKSP_DATABASELABE"."ADMINISTRADORES" (
    "NOME" VARCHAR2(80 char),
    "TELEFONE"  NUMBER(9), 
    "E-MAIL" VARCHAR2(80 char),
    "URL" VARCHAR2(80 char),
    "CNPJ"  NUMBER(14) NOT NULL
);

CREATE TABLE "WKSP_DATABASELABE"."COTACOES" (
    "TICKER" VARCHAR2(6 char) NOT NULL,
    "DATA_COTA" DATE NOT NULL,
    "COTA_ATUAL" NUMBER(38) NOT NULL, 
    "REDIMENTO_ATUAL" NUMBER(38) NOT NULL,
    "MINIMO_COTA" DECIMAL(5) NOT NULL,
    "MAXIMO_COTA" DECIMAL(5) NOT NULL,
    "ABERTURA" DECIMAL(5) NOT NULL,
    "FECHAMENTO" DECIMAL(5) NOT NULL,
    "VOLUME_COTAS" INT NOT NULL,
    "MES" DATE NOT NULL
);

CREATE TABLE "WKSP_DATABASELABE"."DIVIDENDOS"(
    "TICKER" VARCHAR2(6 char) NOT NULL,
    "DATA_COTA" DATE NOT NULL,
    "COTA_ATUAL" NUMBER(38) NOT NULL,
    "ULT_DIVID" NUMBER(3),
    "DY_ULT" NUMERIC(3),
    "DIV_ACAO" NUMBER(3),
    "DIV_YIELD" NUMBER(3)
);

/*
* INDEX
*/
CREATE INDEX "WKSP_DATABASELABE"."COTACOES_VOLUME_COTAS_IDX" ON "WKSP_DATABASELABE"."COTACOES" ("VOLUME_COTAS");

/*
* CHAVE PRIMARIAS
**/
ALTER TABLE "WKSP_DATABASELABE"."FUNDOS"
    ADD CONSTRAINT "PK_TICKER"
    PRIMARY KEY("TICKER");
    
     
 /*
 * CHAVE ESTRANGEIRAS
 **/   
ALTER TABLE "WKSP_DATABASELABE"."COTACOES"
    ADD CONSTRAINT "COTACOES_TICKER_FK"
    FOREIGN KEY ("TICKER")
    REFERENCES "WKSP_DATABASELABE"."FUNDOS" ("TICKER");