CREATE TABLE FUNDOS ( 
    TICKER VARCHAR2(6 char) NOT NULL,
    TIPO_ABBIMA VARCHAR2(64) NOT NULL,
    SEGMENTO VARCHAR2(64 char),
    CONTA_EMIT  NUMBER(38) NOT NULL,
    NUM_COTAS  NUMBER(38) NOT NULL,
    RAZAO_SOCIAL VARCHAR2(38 char) NOT NULL,
    CNPJ  NUMBER(14) NOT NULL,
    NOME_PREGAO VARCHAR2(80 char) NOT NULL,
    PRAZO_DURACAO VARCHAR2(80 char),
    TIPO_GESTAO VARCHAR2(60 char),
    CNPJ_ADMIN  NUMBER(14) NOT NULL
);

CREATE TABLE ADMINISTRADORES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- CHAVE PRIMARIA AUTO INCREMENTADA
    NOME VARCHAR2(80 char) NOT NULL,
    TELEFONE  NUMBER(12), 
    EMAIL VARCHAR2(80 char),
    URL_SITE VARCHAR2(80 char),
    CNPJ  NUMBER(14) NOT NULL
);

CREATE TABLE COTACOES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- CHAVE PRIMARIA AUTO INCREMENTADA
    TICKER VARCHAR2(6 char) NOT NULL,
    DATA_COTA DATE NOT NULL,
    COTA_ATUAL NUMBER(38) NOT NULL, 
    REDIMENTO_ATUAL NUMBER(38) NOT NULL,
    MINIMO_COTA DECIMAL(5) NOT NULL,
    MAXIMO_COTA DECIMAL(5) NOT NULL,
    ABERTURA DECIMAL(5) NOT NULL,
    FECHAMENTO DECIMAL(5) NOT NULL,
    VOLUME_COTAS INT NOT NULL,
    MES DATE NOT NULL
);

CREATE TABLE DIVIDENDOS(
    TICKER VARCHAR2(6 char) NOT NULL,
    DATA_COTA DATE NOT NULL,
    COTA_ATUAL NUMBER(38) NOT NULL,
    ULT_DIVID NUMBER(3),
    DY_ULT NUMERIC(3),
    DIV_ACAO NUMBER(3),
    DIV_YIELD NUMBER(3)
);

/*
* INDEX
*/
CREATE INDEX COTACOES_VOLUME_COTAS_IDX ON COTACOES (VOLUME_COTAS);

/*
* CHAVE PRIMARIAS
**/
ALTER TABLE FUNDOS
    ADD CONSTRAINT PK_TICKER
    PRIMARY KEY(TICKER);

ALTER TABLE ADMINISTRADORES
    ADD CONSTRAINT PK_CNPJ
    PRIMARY KEY(CNPJ);
       
 /*
 * CHAVE ESTRANGEIRAS
 **/
ALTER TABLE FUNDOS
    ADD CONSTRAINT FUNDOS_CNPJ_FK
    FOREIGN KEY (CNPJ_ADMIN)
    REFERENCES ADMINISTRADORES (CNJ);

ALTER TABLE COTACOES
    ADD CONSTRAINT COTACOES_TICKER_FK
    FOREIGN KEY (TICKER)
    REFERENCES FUNDOS (TICKER);

ALTER TABLE DIVIDENDOS
    ADD CONSTRAINT DIVIDENDOS_TICKER_FK
    FOREIGN KEY (TICKER)
    REFERENCES FUNDOS (TICKER);